repos:
  - repo: local
    hooks:
      - id: clean-project
        name: clean any unused files
        entry: bash ./build.sh clean
        language: system
        pass_filenames: false

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: v0.16.6
    hooks:
      - id: cython-lint
      - id: double-quote-cython-strings
