[project]
name = "mega"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cython>=3.1.0",
    "numpy>=2.2.6",
    "pre-commit>=4.2.0",
    "scipy>=1.15.3",
    "setuptools>=80.7.1",
]
